// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPreferences() {
  return window['go']['user_preferences']['userPreferencesGenerator']['GetPreferences']();
}

export function SetPreference(arg1, arg2) {
  return window['go']['user_preferences']['userPreferencesGenerator']['SetPreference'](arg1, arg2);
}
