// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetPreferences():Promise<types.UserPreferences>;

export function SetPreference(arg1:types.UserPreferencesKeys,arg2:any):Promise<void>;
