// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WriteLog(arg1, arg2) {
  return window['go']['app_logging']['loggingManager']['WriteLog'](arg1, arg2);
}
