// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenIssueReport():Promise<void>;

export function SaveFile(arg1:string):Promise<void>;
